openapi: 3.1.0
info:
  title: Student API
  description: API documentation for Student management
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /students:
    post:
      summary: Create a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentRequest'
      responses:
        '201':
          description: Student created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentResponse'
    get:
      summary: Get all students
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentResponse'
  /students/{id}:
    get:
      summary: Get student by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Student found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentResponse'
components:
  schemas:
    StudentRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    StudentResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string